# Default values for senik-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategyType: Recreate

image:
  repository: debezium/postgres
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "14"

container:
  port: 5432

volume:
  mountPath: /var/lib/postgresql/data

pvc:
  accessMode: ReadWriteOnce
  storage: 500Mi

service:
  type: ClusterIP
  port: 5432
