version: "3"
services:

  db:
    image: debezium/postgres:14
    ports:
      - "65432:5432"
    environment:
      POSTGRES_USER: "senik"
      POSTGRES_PASSWORD: "senik"
      POSTGRES_DB: "senik"
    volumes:
      - senik-volume:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      # bypass error: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
      sonar.search.javaAdditionalOpts: "-Dnode.store.allow_mmap=false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  sonarqube-db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data



volumes:
  senik-volume:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
