apiVersion: v1
kind: Service
metadata:
  labels:
    app: senik
  name: senik-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: senik
  type: ClusterIP
