spring:
  jpa:
    open-in-view: false
    # two lines bellow needed for not logging query twice
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        ddl-auto: validate
        use-new-id-generator-mappings: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
  flyway:
    enabled: true
  #    json serde by default:

  kafka:
    bootstrap-servers:
      - localhost:9093
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      isolation-level: read_committed # used in autoconfigured ConcurrentKafkaListenerContainerFactory
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  output:
    ansi:
      enabled: always # needed because when running tests in intellij ansi is not rendered otehrwise
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

okta:
  oauth2:
    issuer: https://dev-12550077.okta.com/oauth2/default
    clientId: 0oa54gy6kbqpXlYeu5d7
    clientSecret: OdRy6Akv2_tE7qD9H6eiIsQZMRIgDBTMWqQFkyKm

springdoc:
  default-produces-media-type: application/json
  paths-to-exclude: /internal-api/** # ff4j


ff4j:
  web-console:
    enabled: true
  audit:
    enabled: true
  api:
    spring-doc:
      enabled: false
    context-path: "/internal-api/ff4j" #just to differentiate from our api

cors:
  allowedOrigins:
    - "http://localhost:4200" # local dev mode
    - "http://localhost:8081" # local k3d cluster

