apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "senik-db.labels" . | nindent 4 }}
  name: {{ include "senik-db.fullname" . }}-claim
spec:
  storageClassName: local-path-retain
  accessModes:
    - {{ .Values.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
