# Environment-specific values.

config:
  datasourcePrefix: "jdbc:postgresql://"
  datasourcePort: 5432
  db: "senik"
  dbUser: "senik"
  dbPassword: "senik"
  allowedOrigins: "https://www.senik.tk"

senik-app:
  service:
    #  for alb to work we need NodePort
    type: NodePort
    port: 80
  ingress:
    hosts:
      - host: api.senik.tk
        paths:
          - path: /
            port: 80
  image:
    repository: otinanism/senik
    pullPolicy: Always

senik-db:
  awsStorage: true
  storageClass: gp2
