# Environment-specific values.

config:
  datasourcePrefix: "jdbc:postgresql://"
  datasourcePort: 5432
  db: "senik"
  dbUser: "senik"
  dbPassword: "senik"
  allowedOrigins: "https://dev.senik.tk"

senik-app:
  service:
    #  for alb to work we need NodePort
    type: NodePort
    port: 80
  ingress:
    hosts:
      - host: devapi.senik.tk
        paths:
          - path: /
            port: 80
  image:
    repository: otinanism/senik
    pullPolicy: Always

senik-db:
  awsStorage: true
# TODO: for kops we need to use default storag class to avoid error  'had no available volume zone'
#  storageClass: gp2

