# Environment-specific values.

config:
  datasourcePrefix: "jdbc:postgresql://"
  datasourcePort: 5432
  db: "senik"
  dbUser: "senik"
  dbPassword: "senik"
  allowedOrigins: "http://localhost:8081"


senik-app:
  ingress:
    local: true
    hosts:
      - host: kubernetes.docker.internal
        paths:
          - path: /
            port: 80

senik-db:
  storageClass: local-path-retain
