apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "senik-app.fullname" . }}-ingress
  labels:
    {{- include "senik-app.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "senik-app.fullname" . }}-service
                port:
                  number: {{ .Values.ingress.port }}
