apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "senik-app.fullname" . }}-ingress
  labels:
    {{- include "senik-app.labels" . | nindent 4 }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
    # share a single ALB with all ingress rules with search-app-ingress
    alb.ingress.kubernetes.io/group.name: senik
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "senik-app.fullname" . }}-service
                port:
                  number: {{ .Values.ingress.port }}
      {{- if .Values.ingress.host}}
      host: {{ .Values.ingress.host }}
      {{- end }}
