apiVersion: v1
kind: Service
metadata:
  name: {{ include "senik-app.fullname" . }}-service
  labels:
    {{- include "senik-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "senik-app.selectorLabels" . | nindent 4 }}
